apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cashaddress-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - cashaddress.org
    - www.cashaddress.org
    secretName: cashaddress-tls
  defaultBackend:
    service:
      name: cashaddress
      port:
        number: 88
  rules:
  - host: cashaddress.org
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: cashaddress
            port:
              number: 88
  - host: www.cashaddress.org
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: cashaddress
            port:
              number: 88
